nelmio_api_doc:
    documentation:
        info:
            title: Symfony REST API
            description: Symfony 5 version
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - login
                        - jwt
                        - token
                    summary: Authenticate and get JWT token.
                    requestBody:
                        description: Authenticate and get JWT token.
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Authenticated.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
    areas:
        path_patterns:
            - ^/api(?!/doc$)